#  Created By: Mahmoud El Shenawy (Dev.M.ElShenawy@Icloud.com)
name: opticore
description: OptiCore is a lightweight micro-framework for Flutter that simplifies and optimizes your app development
version: 1.0.2
homepage: https://github.com/dev-mahmoud-elshenawy/OptiCore
repository: https://github.com/dev-mahmoud-elshenawy/OptiCore
issue_tracker: https://github.com/dev-mahmoud-elshenawy/OptiCore/issues
license: MIT

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.6
  talker: ^4.5.5
  dio: ^5.7.0
  bot_toast: ^4.1.3
  font_awesome_flutter: ^10.8.0
  lottie: ^3.2.0
  equatable: ^2.0.7
  flutter_svg: ^2.0.16
  internet_connection_checker_plus: ^2.7.0
  connectivity_plus: ^6.1.1
  cached_network_image: ^3.4.1
  modal_bottom_sheet: ^3.0.0
  talker_dio_logger: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/anim/
    - assets/icon/